page:
  from: 1
  to: 10

# Other blacklist_domains
#'openload',
# 'hqq.tv'
blacklist_domains:
  - 'kannadamovies'
  - 'topbestsite'

blacklist_titles:
  - 'telugu'
  - 'tamil'
  - 'hindi'
  - 'malayalam'
  - 'kannada-serial'
  - 'Kannada Serial'
  - 'dance-karnataka-dance-family'
  - 'family-doctor'
  - 'khiladi-kutumba'
  - 'majaa-bharatha'
  - 'majaa-bjaratha'
  - 'Majaa Bjaratha'
  - 'Majaa Bharatha'
  - 'Nandhini'
  - 'oggarane-dabbi'
  - 'Sa_Re_Ga_Ma_Pa'
  - 'sa_re_ga_ma_pa'
  - 'Shantam Paapam'
  - 'shantam-paapam'
  - 'Super Talk Time'
  - 'super-talk-time'
  - 'swaraabhisheka'
  - 'dance-dance-juniors'
  - 'drama-juniors-season'
  - 'ganesha-na-ninna-bidalaare'
  - 'Majaa Talkies'
  - 'nandhini-'
  - 'Nandhini '
  - 'Sanju Mathu Naanu'
  - 'Super Talk Time'
  - 'super-minute'
  - 'Super Minute'
  - 'Zee Kannada Serial'
  - 'Star Suvarna Kannada Serial'
